branches:
  only:
  - middleman
language: ruby
before_script:
- 
script:
- bash ./deploy/deploy.sh
env:
  global:
  - GH_REPO="utensil/utensil.github.com"
  - secure: qliv3YR2/dxC744o7SjEnFrhTtAGgGrnNV9LM+kZPiyhaMvHfo7cuVKdWkgnkTM9z0gNkOXJIcs4PSV/TzbHEQfc5Y9ia7++tzPz5JNmR3Cko3AwdtZAjkN9EEwSSFynH11zycU+rFT+0qVoEOstrDMirKyVM56U0+TbBpb/lNU=
